import { insightItemId } from "@/components/dashboard/itemIds";
import { VoteButtons } from "@/components/dashboard/VoteButtons";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { DashboardSection, InsightData } from "@/services/apiClient";

type InsightPanelProps = {
  section: DashboardSection<InsightData> | undefined;
  generatedAt?: string;
  loading?: boolean;
};

export function InsightPanel({
  section,
  generatedAt = "",
  loading = false,
}: InsightPanelProps) {
  const insight = section?.data;

  return (
    <Card className="animate-in fade-in h-full duration-300">
      <CardHeader>
        <CardTitle>AI insight</CardTitle>
        <CardDescription>
          {section?.stale
            ? "Showing a stale insight."
            : insight?.generated_by
              ? `Generated by ${insight.generated_by}`
              : "Daily personalized note"}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {loading ? <p className="text-muted-foreground text-sm">Loading insight…</p> : null}
        {!loading && section?.error ? (
          <p className="text-destructive text-sm" role="alert">
            {section.error.message}
          </p>
        ) : null}
        {!loading && !section?.error && !insight?.insight_text ? (
          <p className="text-muted-foreground text-sm">No insight available.</p>
        ) : null}
        {!loading && insight?.insight_text ? (
          <>
            <p className="text-sm leading-relaxed whitespace-pre-wrap">{insight.insight_text}</p>
            <VoteButtons
              itemId={insightItemId(generatedAt)}
              itemType="insight"
            />
          </>
        ) : null}
      </CardContent>
    </Card>
  );
}
